#!/bin/bash
set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATES_DIR="$REPO_ROOT/templates"
YAML_DIR="$REPO_ROOT/yaml"

# Source common functions
source "$SCRIPT_DIR/common.sh"

echo "=========================================="
echo "Deploying Mattermost with NFS Storage"
echo "=========================================="

# Load and validate configuration
load_and_validate_config "$SCRIPT_DIR"

# Verify YAML files exist (should be generated by Makefile)
if [ ! -d "$YAML_DIR" ] || [ ! -f "$YAML_DIR/mattermost-installation-nfs.yaml" ]; then
    print_error "YAML files not found. Please run: make deploy-nfs"
    echo "  (Running deploy scripts directly is not recommended - use Makefile targets instead)"
    exit 1
fi

# Ensure resource group exists
echo "Ensuring resource group exists..."
if ! az group show --name "$RESOURCE_GROUP" &>/dev/null; then
    echo "Creating resource group: $RESOURCE_GROUP in $LOCATION"
    az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
fi

# Create AKS cluster
create_aks_cluster

# Create PostgreSQL database
create_postgresql

# Install cert-manager
install_cert_manager

# Install ALB Controller
install_alb_controller

# Create ALB infrastructure
create_alb_infrastructure

# Create NFS storage resources
echo ""
echo "Creating NFS storage resources..."
echo "  Storage Class: $NFS_STORAGE_CLASS"
echo "  PVC Name: $NFS_PVC_NAME"
echo "  Storage Size: $NFS_STORAGE_SIZE"

# Create namespace
kubectl create namespace mattermost --dry-run=client -o yaml | kubectl apply -f -

echo "Applying NFS storage resources..."
kubectl apply -f "$YAML_DIR/nfs-storage/storage-class.yaml"
kubectl apply -f "$YAML_DIR/nfs-storage/pvc.yaml"

echo "Waiting for PVC to be bound..."
kubectl wait --for=jsonpath='{.status.phase}'=Bound pvc/$NFS_PVC_NAME -n mattermost --timeout=300s || {
    print_warning "PVC binding taking longer than expected"
    echo "Checking PVC status..."
    kubectl get pvc $NFS_PVC_NAME -n mattermost
    kubectl describe pvc $NFS_PVC_NAME -n mattermost
}

# Get actual capacity
PVC_CAPACITY=$(kubectl get pvc $NFS_PVC_NAME -n mattermost -o jsonpath='{.status.capacity.storage}' 2>/dev/null || echo "unknown")
print_success "NFS storage resources created (Capacity: $PVC_CAPACITY)"

# Install Mattermost Operator
install_mattermost_operator

# Create Mattermost namespace and secrets
echo ""
echo "Creating Mattermost secrets..."

# Apply secrets from pre-generated YAML
kubectl apply -f "$YAML_DIR/mattermost-secret-postgres.yaml"
if [ -f "$YAML_DIR/mattermost-secret-license.yaml" ]; then
    kubectl apply -f "$YAML_DIR/mattermost-secret-license.yaml"
fi

print_success "Secrets created"

# Create Gateway API resources (HTTP-only initially)
create_gateway_resources "$YAML_DIR" "$TEMPLATES_DIR"

# Configure DNS and wait for propagation
configure_dns_and_wait

# Provision TLS certificate
provision_tls_certificate "$YAML_DIR" "$TEMPLATES_DIR"

# Deploy Mattermost with NFS
echo ""
echo "Deploying Mattermost with NFS storage..."
kubectl apply -f "$YAML_DIR/mattermost-installation-nfs.yaml"

echo ""
echo "Waiting for Mattermost pods to be ready (this may take several minutes)..."
kubectl -n mattermost wait --for=condition=ready pod -l app=mattermost --timeout=600s || echo "Mattermost deployment taking longer than expected, check status manually"

# Validation
echo ""
echo "Validating NFS deployment..."

# Check mount is working
echo "Checking NFS mount..."
if kubectl exec -n mattermost deployment/mattermost -- df -h /mattermost/data &>/dev/null; then
    kubectl exec -n mattermost deployment/mattermost -- df -h /mattermost/data
else
    print_warning "Could not check NFS mount (pods may not be ready yet)"
fi

# Check file permissions
echo "Checking file permissions..."
if kubectl exec -n mattermost deployment/mattermost -- ls -ld /mattermost/data &>/dev/null; then
    kubectl exec -n mattermost deployment/mattermost -- ls -ld /mattermost/data
else
    print_warning "Could not check file permissions (pods may not be ready yet)"
fi

# Final status
echo ""
echo "=========================================="
echo "  NFS Deployment Complete!"
echo "=========================================="
echo ""
echo "Mattermost URL: https://$DOMAIN"
echo "Storage Type: NFS (Azure Files Premium)"
echo ""
echo "NFS Configuration:"
echo "  PVC Name: $NFS_PVC_NAME"
echo "  Storage Class: $NFS_STORAGE_CLASS"
echo "  Capacity: $PVC_CAPACITY"
echo ""
echo "PVC Status:"
kubectl get pvc -n mattermost
echo ""
echo "To check deployment status:"
echo "  make status"
echo ""
echo "To verify NFS volume is mounted:"
echo "  kubectl exec -n mattermost deployment/mattermost -- df -h /mattermost/data"
echo ""
echo "To view logs:"
echo "  make logs-mattermost"
echo ""
