#!/bin/bash
set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TEMPLATES_DIR="$REPO_ROOT/templates"
YAML_DIR="$REPO_ROOT/yaml"

# Source common functions
source "$SCRIPT_DIR/common.sh"

echo "============================================"
echo "Deploying Mattermost with S3Proxy Storage"
echo "============================================"

# Load and validate configuration
load_and_validate_config "$SCRIPT_DIR"

# Verify YAML files exist (should be generated by Makefile)
if [ ! -d "$YAML_DIR" ] || [ ! -f "$YAML_DIR/mattermost-installation-s3proxy.yaml" ]; then
    print_error "YAML files not found. Please run: make deploy-s3proxy"
    echo "  (Running deploy scripts directly is not recommended - use Makefile targets instead)"
    exit 1
fi

# Ensure resource group exists
echo "Ensuring resource group exists..."
if ! az group show --name "$RESOURCE_GROUP" &>/dev/null; then
    echo "Creating resource group: $RESOURCE_GROUP in $LOCATION"
    az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
fi

# Create AKS cluster
create_aks_cluster

# Create PostgreSQL database
create_postgresql

# Install cert-manager
install_cert_manager

# Install ALB Controller
install_alb_controller

# Create ALB infrastructure
create_alb_infrastructure

# Create Azure Storage Account and Container
echo ""
echo "Creating Azure Storage Account and Container..."
echo "  Storage Account: $S3PROXY_STORAGE_ACCOUNT"
echo "  Container: $S3PROXY_CONTAINER"
echo "  Location: $LOCATION"

# Check if storage account exists
if ! az storage account show --name "$S3PROXY_STORAGE_ACCOUNT" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
    echo "Creating storage account..."
    az storage account create \
        --name "$S3PROXY_STORAGE_ACCOUNT" \
        --resource-group "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --sku "$S3PROXY_STORAGE_SKU" \
        --kind StorageV2 \
        --allow-blob-public-access false \
        --https-only true
    print_success "Storage account created"
else
    echo "Storage account already exists"
fi

# Get storage account key
echo "Retrieving storage account key..."
AZURE_STORAGE_KEY=$(az storage account keys list \
    --resource-group "$RESOURCE_GROUP" \
    --account-name "$S3PROXY_STORAGE_ACCOUNT" \
    --query '[0].value' \
    --output tsv)

if [ -z "$AZURE_STORAGE_KEY" ]; then
    print_error "Failed to retrieve storage account key"
    exit 1
fi

# Create container if it doesn't exist
if ! az storage container show --name "$S3PROXY_CONTAINER" --account-name "$S3PROXY_STORAGE_ACCOUNT" --account-key "$AZURE_STORAGE_KEY" &>/dev/null; then
    echo "Creating blob container..."
    az storage container create \
        --name "$S3PROXY_CONTAINER" \
        --account-name "$S3PROXY_STORAGE_ACCOUNT" \
        --account-key "$AZURE_STORAGE_KEY" \
        --public-access off
    print_success "Container created"
else
    echo "Container already exists"
fi

print_success "Azure Storage resources configured"

# Create S3Proxy namespace and resources
echo ""
echo "Deploying S3Proxy..."
echo "  Namespace: $S3PROXY_NAMESPACE"
echo "  Image: $S3PROXY_IMAGE"

# Create namespace
kubectl create namespace "$S3PROXY_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

# Create Azure Storage credentials secret
echo "Creating Azure Storage credentials secret..."
kubectl create secret generic azure-storage-credentials \
    --from-literal=account-name="$S3PROXY_STORAGE_ACCOUNT" \
    --from-literal=account-key="$AZURE_STORAGE_KEY" \
    --namespace="$S3PROXY_NAMESPACE" \
    --dry-run=client -o yaml | kubectl apply -f -

# Deploy S3Proxy resources
echo "Applying S3Proxy resources..."
kubectl apply -f "$YAML_DIR/s3proxy/secret-credentials.yaml"
kubectl apply -f "$YAML_DIR/s3proxy/deployment.yaml"
kubectl apply -f "$YAML_DIR/s3proxy/service.yaml"

# Wait for S3Proxy to be ready
echo "Waiting for S3Proxy pods to be ready..."
kubectl -n "$S3PROXY_NAMESPACE" wait --for=condition=ready pod -l app=s3proxy --timeout=300s || {
    print_warning "S3Proxy deployment taking longer than expected"
    kubectl get pods -n "$S3PROXY_NAMESPACE"
}

print_success "S3Proxy deployed successfully"

# Install Mattermost Operator
install_mattermost_operator

# Create Mattermost namespace and secrets
echo ""
echo "Creating Mattermost secrets..."

# Create namespace
kubectl create namespace mattermost --dry-run=client -o yaml | kubectl apply -f -

# Apply secrets from pre-generated YAML
kubectl apply -f "$YAML_DIR/mattermost-secret-postgres.yaml"
kubectl apply -f "$YAML_DIR/mattermost-secret-s3proxy.yaml"
if [ -f "$YAML_DIR/mattermost-secret-license.yaml" ]; then
    kubectl apply -f "$YAML_DIR/mattermost-secret-license.yaml"
fi

print_success "Secrets created"

# Create Gateway API resources (HTTP-only initially)
create_gateway_resources "$YAML_DIR" "$TEMPLATES_DIR"

# Configure DNS and wait for propagation
configure_dns_and_wait

# Provision TLS certificate
provision_tls_certificate "$YAML_DIR" "$TEMPLATES_DIR"

# Deploy Mattermost with S3Proxy
echo ""
echo "Deploying Mattermost with S3Proxy storage..."
kubectl apply -f "$YAML_DIR/mattermost-installation-s3proxy.yaml"

echo ""
echo "Waiting for Mattermost pods to be ready (this may take several minutes)..."
kubectl -n mattermost wait --for=condition=ready pod -l app=mattermost --timeout=600s || echo "Mattermost deployment taking longer than expected, check status manually"

# Validation
echo ""
echo "Validating S3Proxy deployment..."

# Check S3Proxy pods
echo "S3Proxy pods:"
kubectl get pods -n "$S3PROXY_NAMESPACE"

# Check Mattermost pods
echo ""
echo "Mattermost pods:"
kubectl get pods -n mattermost

# Final status
echo ""
echo "============================================"
echo "  S3Proxy Deployment Complete!"
echo "============================================"
echo ""
echo "Mattermost URL: https://$DOMAIN"
echo "Storage Type: S3Proxy + Azure Blob Storage"
echo ""
echo "S3Proxy Configuration:"
echo "  Namespace: $S3PROXY_NAMESPACE"
echo "  Storage Account: $S3PROXY_STORAGE_ACCOUNT"
echo "  Container: $S3PROXY_CONTAINER"
echo "  Service: s3proxy.$S3PROXY_NAMESPACE.svc.cluster.local"
echo ""
echo "To check deployment status:"
echo "  make status"
echo ""
echo "To view S3Proxy logs:"
echo "  kubectl logs -n $S3PROXY_NAMESPACE -l app=s3proxy"
echo ""
echo "To view Mattermost logs:"
echo "  make logs-mattermost"
echo ""
